### ISSUE TITLE
Dynamic redirect URL

### ISSUE THREAD

**Issue by killemalljustice** [edalzell/laravel-passwordless-login#10]
Hi, is possible to implement a dynamic redirect url ?? something like this

```
$user = User::find(1);
$generator = new LoginUrl($user);
$redirect_url = "/home";
$url = $generator->generate($redirect_url);
```
Thanks.

**Comment by edgrosvenor** [comment]
I like this idea. Do you think you could do a PR to make it happen?

**Comment by killemalljustice** [comment]
I don't have enough knowledge to do it :(

**Comment by edgrosvenor** [comment]
No worries. It's a great idea and we'll find a way to get it in here. Thank you!

**Comment by edgrosvenor** [comment]
@killemalljustice This works now. Two different ways. Check out the readme for details. Thanks for the great idea!

**Comment by killemalljustice** [comment]
> @killemalljustice This works now. Two different ways. Check out the readme for details. Thanks for the great idea!

Thanks to you 👍
