### ISSUE TITLE
Missing required parameters for [Route: magic-login] [URI: magic-login/{expires}/{uid}].

### ISSUE THREAD

**Issue by killemalljustice** [edalzell/laravel-passwordless-login#21]
Hi, i don´t know if i am doing something wrong, but this is my controller:

```
    function sendLoginLink()
    {
        $user = User::find(8);

        $generator = new LoginUrl($user);
        $generator->setRedirectUrl('/home');
        $url = $generator->generate();

        return $url;
    }
```
and when i test the url a got this:

> Illuminate\Routing\Exceptions\UrlGenerationException
> Missing required parameters for [Route: magic-login] [URI: magic-login/{expires}/{uid}].

I am in laravel 7.0.8 with default user model, but with a custom table name and password field.

What could be the problem? 

Thanks.

**Comment by edgrosvenor** [comment]
@killemalljustice I'm spinning up a site matching that description and will get back to you as soon as I have an idea. To be sure, your user table does have an id column, right? I have that hard-coded right now as the primary key, though I'm going to change that to use the primary key defined by the model if it exists.

**Comment by killemalljustice** [comment]
I forgot that also i have a custom id column

```
protected $table = 'GEN_Usuarios';
protected $primaryKey = 'GEN_idUsuarios';
```

**Comment by edgrosvenor** [comment]
OK. Then what I'm working on might fix that for you.

**Comment by killemalljustice** [comment]
Great! 👍

**Comment by edgrosvenor** [comment]
@killemalljustice This should be fixed along with another couple of ugly bugs. Let me know if the problem persists, but I'm closing because I feel good about the fix.

**Comment by edgrosvenor** [comment]
@killemalljustice Nope. I was wrong. Pull in 1.1.3. Sorry. I had created the pull request with the fix but hadn't merged it before I did the release.

**Comment by killemalljustice** [comment]
Hi, i am on 1.1.3 and now the url is generated fine :)

`http://localhost:8080/magic-login/1584098369/8?redirect_to=%2Fhome&user_type=app-user&signature=3871eeb84d3450634360b5852d8bc63c7f80c558d07be176bcf81f60ea9b6c77`

But, when i use it in the browser i got kicked back to login

I am redirecting to /home , and my route is something like this:

```
Route::group(['middleware' => 'auth'], function () {
    Route::view('/home', 'dashboard');
});
```

**Comment by killemalljustice** [comment]
I made this change in the login method from LaravelPasswordlessLoginController, before the return i logged the user by id with this:

```
Auth::loginUsingId(Auth::guard($guard)->user()->GEN_idUsuarios);

return $user->guard_name ? $user->onPasswordlessLoginSuccess($request) : redirect($redirectUrl);
```
And with that now works, so i don´t know what is the problem.

**Comment by edgrosvenor** [comment]
@killemalljustice Does your user model implement the Illuminate\Contracts\Auth\Authenticatable  contract? If it doesn't that's why loginUsingId() works but login() doesn't. The standard way a Laravel model would implement that contract is to extend the Illuminate\Foundation\Auth\User class. Usually something like this:

```
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
```

**Comment by killemalljustice** [comment]
Yes, my user model is implementing the Authenticable contract, but now i know why was not working, i forgot that i was using a custom guard lol, now is working as it should.

One last thing, i set LPL_LOGIN_ROUTE_EXPIRES to 1 , but the link expires in 30 minutes anyways.

Thanks.

**Comment by edgrosvenor** [comment]
@killemalljustice Thanks. I'll take a look at the expiration thing.
