### ISSUE TITLE
Login route expires after first use

### ISSUE THREAD

**Issue by killemalljustice** [edalzell/laravel-passwordless-login#28]
Hi, i was thinking that maybe should be a variable that determine if the login route should expire after the first use, something like this:

LPL_LOGIN_ROUTE_EXPIRES_AFTER_FIRST_USE=true

Then you will have two expirations settings, whatever happends first (the minutes have passed or after first use)

Thanks.

**Comment by edgrosvenor** [comment]
@killemalljustice I might be open to that, but the thing I'm trying to avoid here is having to rely on a database. That's why I'm using signed routes instead of a stored token. Can you think of a clean way of marking a route expired without having to add a migration to the package?

**Comment by php-rock** [comment]
All already used tokens could be stored to the cache.

**Comment by edgrosvenor** [comment]
@php-rock That's actually a pretty interesting solution. can anyone here provide a PR to make this happen?

**Comment by edgrosvenor** [comment]
Thanks for your help @innoflash. Merged it in.
