### ISSUE TITLE
Integration with Sanctum: Custom error message on invalid signature

### ISSUE THREAD

**Issue by kamiben** [edalzell/laravel-passwordless-login#29]
I'm in the process of integrating laravel-passwordless-login  with my Vuejs SPA.
Using : 
- laravel-passwordless-login1.1.3
- Sanctum 2.2.0

Sanctum is used here only as an SPA login, so there is no token issued after login. Authentication is only cookie based.

I generate the  magic link from an API endpoint, and then prepend the generated link with my SPA url, having a dedicated view that does the magic-login GET with axios, with the url appended.

It does work, the cookies are set, but in the case the signature is invalid (corrupted or time expired), I need to display a message to the user (as the 401 is only in the Ajax call). 

I customized the grosv/laravel-passwordless-login/src/LaravelPasswordlessLoginController.php
with : 
 ` abort_if(!$request->hasValidSignature(), 401,'The link is not valid'); `

Do you think it would be a good idea to add an ability to customize this message with config ?
Is it worthy of a pull request ?

**Comment by edgrosvenor** [comment]
@kamiben I would welcome a pull request that makes the message configurable.

**Comment by kamiben** [comment]
Here it is : #32
