### ISSUE TITLE
Magic link never expire despite a set expiration

### ISSUE THREAD

**Issue by kamiben** [edalzell/laravel-passwordless-login#30]
I may have discovered an issue with the package : 

**How to reproduce** : generate a link and wait for it to expire. The link will still work.

**Analysis**
When the magic link is generated, it is generated against the following route 

     Route::get(
        //config('laravel-passwordless-login.login_route').'/{expires}/{uid}',
        config('laravel-passwordless-login.login_route').'/{uid}',
        [LaravelPasswordlessLoginController::class, 'login']
    )->middleware('web')->name(config('laravel-passwordless-login.login_route_name'));

As such, the expires parameter is coded in the path, and not as a parameter. (&expires=timestamp)

However, Laravel's function signatureHasNotExpired (in laravel/framework/src/Illuminate/Routing/UrlGenerator.php) expects the expires data as a parameter. If it is not present the link is simply considered a non expiring signed link.

      public function signatureHasNotExpired(Request $request)
         {
        $expires = $request->query('expires');
        return ! ($expires && Carbon::now()->getTimestamp() > $expires);
          }

So the function returns true and simply tests the signature which is correct. The user is now authenticated.

I have implemented the following fix : not using the expires as a paremeter : this way expires is set as a parameter again and not include it in the route: 

     Route::get(
        //config('laravel-passwordless-login.login_route').'/{uid}',
        config('laravel-passwordless-login.login_route').'/{uid}',
        [LaravelPasswordlessLoginController::class, 'login']
    )->middleware('web')->name(config('laravel-passwordless-login.login_route_name'));

That way : the url is still signed (against all parameters, including expiration, so still secure), the signatureHasNotExpired works and the link expires as inteded.

I'll submit a PR to discuss the change.

**Comment by kamiben** [comment]
See PR #31  for resolution

**Comment by edgrosvenor** [comment]
@kamiben Your PR has been merged in and a new release has been tagged. Thank you!
