### ISSUE TITLE
Custom Redirect URL not working if Guard Name attribute trait is set

### ISSUE THREAD

**Issue by afzafri** [edalzell/laravel-passwordless-login#50]
Hi,
First of all, thank you for this great package, it has been really great.

My requirement is to have user auto redirected to a dynamic route, depending on what "post" they are going to see.
However, I am not able to have the custom redirect URL to be working using the following code:

```php
$id = 'postid';
$generator = new LoginUrl($user);
$generator->setRedirectUrl('/post/'.$id); 
$url = $generator->generate();
```

Currently I have 2 type of users, let say its "User" and "Admin". So I need to set the Guard for each users right.
Therefore I used the Traits of this package, because with the traits I can set the Guard Name.

So I did some digging into the package codes, and I noticed that on [Line 54 of LaravelPasswordlessLoginController.php](https://github.com/grosv/laravel-passwordless-login/blob/3680d7ef1bf11f12322e60a7ab73b0fbc0da8fe8/src/LaravelPasswordlessLoginController.php#L54) :

```php
        return $user->guard_name ? $user->onPasswordlessLoginSuccess($request) : redirect($redirectUrl);
```

This line here check if the Guard Name attribute for the User model is set or not. If it does set, then it will proceed to call the [onPasswordlessLoginSuccess()](https://github.com/grosv/laravel-passwordless-login/blob/3680d7ef1bf11f12322e60a7ab73b0fbc0da8fe8/src/Traits/PasswordlessLogin.php#L74) method, in which it's actually redirect the user to the route defined in [getRedirectUrlAttribute()](https://github.com/grosv/laravel-passwordless-login/blob/3680d7ef1bf11f12322e60a7ab73b0fbc0da8fe8/src/Traits/PasswordlessLogin.php#L47) of the Model.

So if I used the included Traits, the custom redirect url method, `setRedirectUrl()` will not be used at all since it will keep fall back to use the `redirect_url `attribute in the Model.

Is this supposed to be designed this way, and I am doing something incorrect in my implementation?

Currently, to overcome this problem, I also need to override the  `onPasswordlessLoginSuccess($request)` method in both my user Models like the following:

```php
public function onPasswordlessLoginSuccess($request)
{
    # check if custom url set, redirect to the url
    return ($request->has('redirect_to')) ? redirect($request->redirect_to) : redirect($this->getRedirectUrlAttribute());
}
```

Again, thank you for this package, really great package. If I am doing something wrong in my implementation, please guide me. 
Thanks!

**Comment by edgrosvenor** [comment]
It looks like you're right. Do you think you'd be up to providing a PR to fix this? I have a few PRs sitting in there waiting for me and I'm going to try to free up some time next week to get them reviewed and merged in. I can try to handle this as well, but a PR at least demonstrating exactly how you'd like to see it work would be a huge help.

**Comment by afzafri** [comment]
Hi @edgrosvenor , sorry for the late reply. I have opened a pull request to propose a fix for this issue. Thank you

**Comment by edgrosvenor** [comment]
@afzafri Looks good. Thank you. I've merged it in and am tagging a release now.
