### ISSUE TITLE
Class 'App\Http\Controllers\PasswordlessLogin' not found after installing

### ISSUE THREAD

**Issue by Tiththa** [edalzell/laravel-passwordless-login#64]
I am getting `Class 'App\Http\Controllers\PasswordlessLogin' not found` after installing via composer, what should i register in `app.php` ? 

Using Laravel 7 with Simple Usage method as in the docs

**Comment by owenvoke** [comment]
It sounds like you need to import the facade with `use Grosv\LaravelPasswordlessLogin\PasswordlessLogin;` at the top of your controller. 🤔 In the example, the facade isn't imported as I'm assuming they added it to their `app.aliases` list in the config.

**Comment by Tiththa** [comment]
> It sounds like you need to import the facade with `use Grosv\LaravelPasswordlessLogin\PasswordlessLogin;` at the top of your controller. 🤔 In the example, the facade isn't imported as I'm assuming they added it to their `app.aliases` list in the config.

Thank you for the help, yes it isn't imported hence it is throwing the error. I will give it another go and check. @owenvoke
