### ISSUE TITLE
Redirect Issue with new Guest Middleware 

### ISSUE THREAD

**Issue by dajoeberlei** [edalzell/laravel-passwordless-login#76]
Hi there,

Big Fan of your package, thanks for your nice work in advance!!

Unfortunately the newly added guest middleware causes a new problem. I have an app that highly relies on the redirect feature of the passwordless login package. Due to the new guest middleware the redirect will not be executed when a user is already logged in because the login method of LaravelPasswordlessLoginController will never be called and as far as i understand it correct after a dive into your package the redirect logic is executed within the login method of this Controller.

The redirect only happens when being logged out and clicking on the generated link.

**Comment by dajoeberlei** [comment]
just to be sure. I downgraded to 1.6.0 and it works fine.

**Comment by edgrosvenor** [comment]
So it sounds like the solution is to create a new middleware that first checks for a redirect and handles it regardless of logged in status and then does the rest of the guest route stuff on anyone who isn't redirected. Does this sound like it would fix it?

**Comment by edgrosvenor** [comment]
@dajoeberlei I've created a branch / PR that I believe fixes this: https://github.com/grosv/laravel-passwordless-login/pull/77

Do you have the ability to pull this branch (replace_guest_middleware) into your project and see if it resolves the issue correctly for you?

**Comment by dajoeberlei** [comment]
@edgrosvenor yes that branch worked fine!

**Comment by edgrosvenor** [comment]
@dajoeberlei Thank you. I've tagged a release that includes the fix.

**Comment by ITango** [comment]
Hello, 

I updated to 1.8, but still have an issue when a user is already logged in. 

The login link is requested from a SPA frontend, however, when a user is already logged in and clicks again on the login link, the Laravel backend home page is opened, not the SPA frontend.

Any suggestions on what I need to check?

Thank you

**Comment by ITango** [comment]
It turned out, that the problem was with the RedirectIfAuthenticated middleware. After I removed the logic and just had the handle method simply do `return $next($request);` it works ok now.

Thank you for your work Ed.
